image: python:latest

stages:
    - linting

isort:
    stage: linting
    tags: 
        - rpl
    script:
        - isort . --check-only
    only:
        - merge_request

black:
    stage: linting
    tags: 
        - rpl
    script:
        - black --check .
    only:
        - merge_request

flake8:
    stage: linting
    tags: 
        - rpl
    script:
        - flake8 .
    only:
        - merge_request

pylint:
    stage: linting
    tags: 
        - rpl
    script:
        - pylint $(find . -iname "*.py")
    only:
        - merge_request