image: python:latest

before_script:
  - python --version  # For debugging
  - pip install isort black flake8 pylint pytest

stages:
    - linting
    - test

isort:
    stage: linting
    tags: 
        - rpl
    script:
        - isort . --check-only
    only:
        - merge_request

black:
    stage: linting
    tags: 
        - rpl
    script:
        - black --check .
    only:
        - merge_request

flake8:
    stage: linting
    tags: 
        - rpl
    script:
        - flake8 .
    only:
        - merge_request

pylint:
    stage: linting
    tags: 
        - rpl
    script:
        - pylint $(find . -iname "*.py")
    only:
        - merge_request

pytest:
    stage: test
    tags:
        - rpl
    script:
        - pytest
    only:
        - merge_request