image: python:3.9

before_script:
  - python --version  # For debugging
  - pip install isort black flake8 pylint pytest pyqt6 db-sqlite3

stages:
    - linting
    - test

isort:
    stage: linting
    script:
        - python -m isort . --check-only

black:
    stage: linting
    script:
        - python -m black --check .

flake8:
    stage: linting
    script:
        - python -m flake8 .

pylint:
    stage: linting
    script:
        - python -m pylint src

pytest:
    stage: test
    tags:
        - rpl
    script:
        - pytest
    only:
        - merge_request